### ISSUE TITLE
[META] v0.8.0 release

### ISSUE THREAD

**Issue by vdh** [Caged/d3-tip#168]
A meta-issue to track what is (and should be) going into the next release. If anyone has an issue or pull request they would like to see included here, mention it or reference this issue.
## Requirements 🏁

Things that need to get resolved before v0.8.0 is released:
- [ ] Add a proper test suite (#165)
- [x] Enable linting (#164)
- [ ] Update documentation
  - [ ] NPM install instructions
  - [ ] Mention the micro libraries dependency change
  - [ ] Mention the change for CommonJS users (#162)
  - [x] Mention the `tip.rootElement` feature (#170, #135)
- [ ] Bump the version in `package.json` and `bower.json`
## Changes 🚧
- [x] d3 Micro Libraries (#161)
- [x] Use `require` to load d3 in CommonJS (#162)
## New features 🎉
- [x] Change the default root DOM element with `tip.rootElement` (#170, #135)
## Bug fixes 🐞
- [x] Fixed typo on `directionSouthEast` / `direction_se` (#120, #121)
- [x] Return gracefully when SVG node is falsy (#88, #96, 5f57d02)
## Wishlist 🚀

Things that would be nice but could be done in a later release:
- [ ] Conversion to ES2015, with Babel to compile the ES5 version
  - [ ] Update ESLint configuration from ES5 to ES2015
  - [ ] Validate with a test suite (#165) to make sure the conversion functions the same
- [ ] Start a change log?

**Comment by Hypercubed** [comment]
Is a goal to keep d3 v3 compatibility?  With the current alpha version if the event was initiated by the v3 API then `d3Selection.event` is null, and therefore `getScreenBBox` fails.

**Comment by vdh** [comment]
@Hypercubed I did make a [`v0.6.x`](https://github.com/Caged/d3-tip/tree/v0.6.x) branch with a few fixes with the intention to maintain compatibility for those still using d3 v3. In theory new features could be back-ported to 0.6, but I'm not sure we'd want to keep maintaining v3 support. Is there anything in particular blocking you from upgrading to d3 v4?

**Comment by Hypercubed** [comment]
Nothing except time...

It looks to me the only thing that prevents the alpha from running with d3 is the `getScreenBBox` function.

**Comment by vdh** [comment]
`^0.6` supports `d3@^3.5.5`, `^0.7` supports `d3@^4.2`, and `^0.8` will be using d3 v4's micro libraries (still compatible with `d3@^4.2`). If you don't want to upgrade to d3 v4, then you'll have to either make a new issue requesting a back-port or make a back-port PR into the `v0.6.x` branch.

**Comment by gseyffert** [comment]
Is there any update on when this will be released? It seems like it's DITW.
I'm using this package in a project and the dependency on `d3` pulls in the whole library, which increases the size of our *compressed* bundle by 50 kb (using `brotli` compression). Considering the usage of this package is a whole 8 lines of code in our codebase, that seems like a high price to pay.
We're using d3 in other parts of our app, but until this package we were able to selectively import the modules we wanted to use vs. the whole library.
I'm more than happy to help contribute if that's what's needed.

**Comment by Caged** [comment]
Closing this as we're now at 0.9.0 with support for many of the remaining items in this list.
